import assert from "node:assert/strict";
import test from "node:test";

async function render(path = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}-${path}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request(`http://localhost${path}`, { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("renders the full-screen interactive portfolio", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Affan Shaikh/);
  assert.match(html, /AFFAN_OS \/ INTERACTIVE PORTFOLIO/);
  assert.match(html, /Explore the lab/);
  assert.match(html, /Move your pointer to shift the room/);
  assert.match(html, /Interactive 3D portfolio/);
  assert.match(html, /3D room objects/);
  assert.match(html, /Technology operations/);
  assert.match(html, /SSIK co-founder/);
  assert.match(html, /Integrity file/);
  assert.match(html, /Server rack/);
  assert.match(html, /3D printer/);
  assert.match(html, /About file/);
  assert.match(html, /Contact file/);
  assert.match(html, /Resume file/);
  assert.match(html, /Inspiration file/);
  assert.match(html, /INDEX/);
  assert.match(html, /room-index-panel/);
  assert.match(html, /room-side-index/);
  assert.match(html, /Quick room navigation/);
  assert.doesNotMatch(html, /Room controls/);
  assert.doesNotMatch(html, /08 ACTIVE OBJECTS/);
  assert.doesNotMatch(html, /href="#room-directory"/);
  assert.doesNotMatch(html, /class="immersive-header"/);
  assert.doesNotMatch(html, /class="immersive-footer"/);
  assert.doesNotMatch(html, /class="immersive-status"/);
  assert.doesNotMatch(html, /href="\/info"/);
  assert.doesNotMatch(html, /href="\/interests"/);
  assert.doesNotMatch(html, /href="\/work\//);
  assert.match(html, /Soundtrack/);
  assert.doesNotMatch(html, /Arch Narrative/i);
});

test("renders the current nonprofit operations case study", async () => {
  const archtechResponse = await render("/work/archtech");
  assert.equal(archtechResponse.status, 200);
  const archtech = await archtechResponse.text();
  assert.match(archtech, /Google Workspace foundation/);
  assert.match(archtech, /Hosting responsibility/);
  assert.match(archtech, /Website team coordination/);
  assert.match(archtech, /Repository.*Private/s);
  assert.match(archtech, /website source and internal project material remain private/i);
});

test("renders SSIK's shared co-founder responsibilities and Affan's additional website work", async () => {
  const response = await render("/work/ssik");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /SSIK IT Consulting &amp; Solutions/);
  assert.match(html, /Ghayas Sher/);
  assert.match(html, /Ontario Tech classmate/);
  assert.match(html, /nine-page public website/);
  assert.match(html, /GitHub Pages/);
  assert.match(html, /share SSIK's co-founder, consulting, security-assessment, privacy-research, and stakeholder-communication responsibilities/i);
  assert.match(html, /In addition to that shared work/i);
  assert.match(html, /12-stage local V1/i);
  assert.match(html, /79 automated tests/i);
  assert.match(html, /outbound delivery disabled/i);
  assert.match(html, /sil6428\.github\.io\/SSIK-website/);
});

test("publishes crawler and structured profile metadata", async () => {
  const response = await render();
  const html = await response.text();
  assert.match(html, /application\/ld\+json/);
  assert.match(html, /ProfilePage/);
  assert.match(html, /Ontario Tech University/);
  assert.match(html, /\/og-lab-v2\.png/);
  assert.match(html, /\/lab-favicon\.svg/);
  assert.doesNotMatch(html, /\/terminal-favicon\.svg/);

  const sitemapResponse = await render("/sitemap.xml");
  assert.equal(sitemapResponse.status, 200);
  const sitemap = await sitemapResponse.text();
  assert.match(sitemap, /work\/archtech/);
  assert.match(sitemap, /work\/ssik/);

  const robotsResponse = await render("/robots.txt");
  assert.equal(robotsResponse.status, 200);
  const robots = await robotsResponse.text();
  assert.match(robots, /Allow: \//);
  assert.match(robots, /sitemap\.xml/i);
});

test("renders the information page", async () => {
  const response = await render("/info");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Ontario Tech University/);
  assert.match(html, /Skills and tools/);
  assert.match(html, /430 hours/);
  assert.match(html, /Explore my interests/);
  assert.doesNotMatch(html, /tel:\+16473091927/);
  assert.match(html, /https:\/\/github\.com\/sil6428/);
  assert.match(html, /Current focus/);
  assert.match(html, /Co-Founder and Website Developer/);
  assert.match(html, /Ghayas Sher/);
  assert.doesNotMatch(html, /src="\/affan-portrait\.png"/);
});

test("renders the expanded interests page", async () => {
  const response = await render("/interests");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Badminton/);
  assert.match(html, /3D printing &amp; design/);
  assert.match(html, /Lord of the Mysteries/);
  assert.match(html, /Reverend Insanity/);
  assert.match(html, /Proxmox home lab/);
  assert.match(html, /Photography/);
  assert.match(html, /https:\/\/sy1len\.vsco\.site/);
  assert.match(html, /court-visual/);
  assert.match(html, /printer-visual/);
  assert.match(html, /books-visual/);
  assert.match(html, /photo-visual/);
  assert.match(html, /rack-visual/);
  assert.match(html, /Read full notes/);
  assert.match(html, /href="\/interests\/badminton"/);
  assert.match(html, /href="\/interests\/3d-printing"/);
});

test("renders all expanded interest notes", async () => {
  const pages = [
    ["/interests/badminton", /Competing at regionals/],
    ["/interests/3d-printing", /From a file to a finished piece/],
    ["/interests/reading", /What I am reading/],
    ["/interests/photography", /What I look for/],
    ["/interests/home-lab", /Why reuse old computers/],
  ];

  for (const [path, expected] of pages) {
    const response = await render(path);
    assert.equal(response.status, 200);
    assert.match(await response.text(), expected);
  }
});

test("includes the device-local soundtrack and hidden terminal", async () => {
  const source = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../app/site-extras.tsx", import.meta.url), "utf8"),
  );
  assert.match(source, /open\.spotify\.com\/playlist/);
  assert.doesNotMatch(source, /open\.spotify\.com\/embed\/playlist/);
  assert.match(source, /1whuIX2zMB3aYGf5oEdCGs/);
  assert.match(source, /window\.localStorage/);
  assert.match(source, /KONAMI_SEQUENCE/);
  assert.match(source, /AFFAN_OS/);
  assert.match(source, /Hidden things and how to find them/);
  assert.match(source, /AFFAN_OS files/);
  assert.match(source, /Three-minute print/);
  assert.match(source, /Original sound effects/);
  assert.match(source, /procedural Web Audio tones/);
  assert.match(source, /sfx-settings/);
  assert.match(source, /Cat trust/);
  assert.match(source, /Printed relic/);
  assert.match(source, /Server beacon/);
  assert.doesNotMatch(source, /cat\.jpg/i);
  assert.match(source, /affan-room-palette/);
  assert.match(source, /affan-room-cat/);
  assert.match(source, /affan-room-relic/);
  assert.match(source, /affan-room-signal/);
  assert.match(source, /affan-os-terminal-toggle/);
  assert.match(source, /document\.querySelector\("\.affan-os"\)/);
  assert.doesNotMatch(source, /PortfolioCat/);
  assert.doesNotMatch(source, /portfolio-cat-swat/);
  assert.doesNotMatch(source, /cat-is-home/);
  const sfx = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../app/site-sfx.ts", import.meta.url), "utf8"),
  );
  assert.match(sfx, /new AudioContext/);
  assert.match(sfx, /affan-portfolio-sfx/);
  assert.match(sfx, /effect === "complete"/);
  assert.match(sfx, /effect === "cat"/);
  assert.doesNotMatch(source, /cat-play-badminton/);
  assert.match(source, /usePathname/);
  assert.match(source, /MobileNavigationTransitions/);
  assert.match(source, /startViewTransition/);
  assert.match(source, /Choose an audio file/);
  assert.match(source, /URL\.createObjectURL/);

  const styles = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  );
  assert.doesNotMatch(styles, /portfolio-cat/);
  assert.doesNotMatch(styles, /cat-footer-visible/);
  assert.doesNotMatch(styles, /cat-house-ready/);
  assert.match(styles, /view-transition-name: mobile-active-tab/);
  assert.match(styles, /max-height: calc\(100svh - 92px\)/);
  assert.match(styles, /max-height: 520px/);
  assert.match(styles, /width: 44px/);
  assert.match(styles, /prefers-reduced-motion: reduce/);

  const topology = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../app/topology-scene.tsx", import.meta.url), "utf8"),
  );
  assert.match(topology, /from "three"/);
  assert.match(topology, /WebGLRenderer/);
  assert.match(topology, /LIVE TOPOLOGY/);

  const room = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../app/interactive-room.tsx", import.meta.url), "utf8"),
  );
  const desktopOs = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../app/desktop-os.tsx", import.meta.url), "utf8"),
  );
  const learningLog = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../app/learning-log-data.generated.ts", import.meta.url), "utf8"),
  );
  const assetCredits = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../THIRD_PARTY_ASSETS.md", import.meta.url), "utf8"),
  );
  const designReferences = await import("node:fs/promises").then(({ readFile }) =>
    readFile(new URL("../DESIGN_REFERENCES.md", import.meta.url), "utf8"),
  );
  assert.match(room, /OrbitControls/);
  assert.match(room, /RoundedBoxGeometry/);
  assert.match(room, /MeshPhysicalMaterial/);
  assert.match(room, /ACESFilmicToneMapping/);
  assert.match(room, /highDetail/);
  assert.match(room, /constrainedDevice/);
  assert.match(room, /pixelRatioLimit/);
  assert.match(room, /mergeGeometries/);
  assert.match(room, /printableBatchCount/);
  assert.match(room, /chess-print-batch-/);
  assert.match(room, /shadowCasterLimit/);
  assert.match(room, /reflectorOnBeforeRender/);
  assert.match(room, /targetFramesPerSecond/);
  assert.match(room, /desktopCovered/);
  assert.match(room, /visibilitychange/);
  assert.doesNotMatch(room, /highDetail \? 2 : 1\.45/);
  assert.doesNotMatch(room, /addDesktopFile/);
  assert.doesNotMatch(room, /OPEN ARCHTECH FILE/);
  assert.doesNotMatch(room, /OPEN ABOUT FILE/);
  assert.doesNotMatch(room, /OPEN CONTACT FILE/);
  assert.doesNotMatch(room, /OPEN RESUME PDF/);
  assert.doesNotMatch(room, /OPEN INSPIRATION FILE/);
  assert.match(room, /https:\/\/bruno-simon\.com\//);
  assert.match(room, /https:\/\/idas-gameboy\.netlify\.app\//);
  assert.match(room, /https:\/\/www\.jesse-zhou\.com\//);
  assert.match(room, /https:\/\/reactbits\.dev\/get-started\/introduction/);
  assert.match(room, /https:\/\/rachelqrwei\.ca\/use/);
  assert.match(room, /https:\/\/github\.com\/rachelqrwei\/personalwebsite/);
  assert.match(room, /https:\/\/threejs\.org\//);
  assert.match(room, /RoomEnvironment/);
  assert.match(room, /Reflector/);
  assert.match(room, /out-of-bounds-reflective-surface/);
  assert.match(room, /out-of-bounds-reflection-tint/);
  assert.match(room, /ROOM_ELEVATION = 0\.48/);
  assert.match(room, /floating-room-platform-base/);
  assert.match(room, /floating-room-platform-lower-trim/);
  assert.match(room, /dark-broad-floorboard/);
  assert.doesNotMatch(room, /graphite-maker-floor-mat/);
  assert.doesNotMatch(room, /maker-floor-mat-inset/);
  assert.doesNotMatch(room, /maker-floor-mat-piping/);
  assert.doesNotMatch(room, /new THREE\.GridHelper/);
  assert.match(room, /reflectionResolution/);
  assert.match(room, /GLTFLoader/);
  assert.match(room, /loadStudioAsset/);
  assert.doesNotMatch(room, /wooden_display_shelves_01_1k\.gltf/);
  assert.match(room, /built-in-stylized-bookshelf/);
  assert.match(room, /dark-studio-pbr-palette/);
  assert.match(room, /flatShading: false/);
  assert.match(room, /Camera_01_1k\.gltf/);
  assert.doesNotMatch(room, /modern_arm_chair_01_1k\.gltf/);
  assert.doesNotMatch(room, /side_table_01_1k\.gltf/);
  assert.doesNotMatch(room, /potted_plant_04_1k\.gltf/);
  assert.doesNotMatch(room, /desk_lamp_arm_01_1k\.gltf/);
  assert.match(room, /#111a24/);
  assert.match(room, /#111622/);
  assert.match(room, /#0e1920/);
  assert.match(room, /baseScale/);
  assert.match(room, /ambient-signal-motes/);
  assert.match(room, /THREE\.Points/);
  assert.match(room, /room-target-cursor/);
  assert.match(room, /room-click-spark/);
  assert.match(room, /room-target-active/);
  assert.match(room, /hover-border-outline/);
  assert.match(room, /THREE\.BackSide/);
  assert.match(room, /applyHoverTreatment/);
  assert.match(room, /restoreHoverTreatment/);
  assert.match(room, /room-spark-active/);
  assert.match(room, /Open resume PDF/);
  assert.doesNotMatch(room, /tel:\+16473091927/);
  assert.match(room, /Affan_Shaikh_Resume\.pdf/);
  assert.match(room, /CanvasTexture/);
  assert.match(room, /wall-decor-collection/);
  assert.match(room, /wall-network-topology-frame/);
  assert.match(room, /wall-photography-triptych/);
  assert.match(room, /#080d15/);
  assert.match(room, /#18152b/);
  assert.doesNotMatch(room, /#a9edcf/);
  assert.match(room, /PROXMOX SERVER RACK/);
  assert.match(room, /3D PRINTER/);
  assert.match(room, /compact-desktop-pc-setup/);
  assert.match(room, /desktop-monitor/);
  assert.match(room, /desktop-mouse/);
  assert.match(room, /desktop-pc-power/);
  assert.match(room, /desktop-monitor-rounded-bezel/);
  assert.match(room, /desktop-monitor-rear-stand/);
  assert.match(room, /desktop-monitor-rear-hinge/);
  assert.match(room, /desktop-screen-power-target/);
  assert.match(room, /CLICK SCREEN TO POWER ON AFFAN_OS/);
  assert.match(room, /INITIALIZING DESKTOP/);
  assert.match(room, /OPEN AFFAN_OS DESKTOP/);
  assert.match(room, /AFFAN_OS READY \/ CLICK SCREEN TO OPEN/);
  assert.match(room, /drawDesktopHandoff/);
  assert.match(room, /drawDesktopBoot\(1\)/);
  assert.doesNotMatch(room, /drawDesktopEnvironment\(\)/);
  assert.match(room, /const powerOffDesktop/);
  assert.match(room, /drawDesktopOff\(\)/);
  assert.match(room, /pcPowerMaterial\.emissiveIntensity = 0/);
  assert.match(room, /focusRef\.current\("__desktop-off"\)/);
  assert.match(room, /activeKey === "__desktop" \? "__desktop-off" : "__overview"/);
  assert.doesNotMatch(room, /desktopPowerTarget\.visible = false/);
  assert.doesNotMatch(room, /desktopFileHitAreas/);
  assert.match(room, /Power on computer desktop/);
  assert.match(room, /DesktopOs/);
  assert.match(room, /desktop-keycap/);
  assert.match(room, /desktop-tower-glass/);
  assert.match(room, /desktop-motherboard/);
  assert.match(room, /desktop-case-fan-ring/);
  assert.match(room, /desktop-case-fan-blade/);
  assert.match(room, /desktop-cpu-block/);
  assert.match(room, /desktop-graphics-card/);
  assert.match(room, /desktop-rgb-memory/);
  assert.match(room, /desktop-mouse-scroll-wheel/);
  assert.match(room, /server-rack-screw/);
  assert.match(room, /server-rack-unit-faceplate/);
  assert.match(room, /server-rack-unit-handle/);
  assert.match(room, /server-rack-rail-hole/);
  assert.match(room, /printer-head-carriage/);
  assert.match(room, /printer-miniature-chess-set/);
  assert.match(room, /chess-board-layer/);
  assert.match(room, /chess-board-square/);
  assert.match(room, /chess-board-beveled-border/);
  assert.match(room, /chess-piece-base-ring/);
  assert.match(room, /chess-piece-lower-base-ring/);
  assert.match(room, /pieceProfiles/);
  assert.match(room, /chess-piece-collar-ring/);
  assert.match(room, /chess-pawn-spherical-head/);
  assert.match(room, /pieceLayer\.name = `chess-\$\{kind\}-layer`/);
  assert.match(room, /\["rook", "knight", "bishop", "queen", "king", "bishop", "knight", "rook"\]/);
  assert.match(room, /chess-rook-battlement/);
  assert.match(room, /chess-rook-crown-ring/);
  assert.match(room, /chess-knight-head/);
  assert.match(room, /chess-knight-snout/);
  assert.match(room, /chess-knight-mane/);
  assert.match(room, /chess-bishop-mitre/);
  assert.match(room, /chess-bishop-mitre-slash/);
  assert.match(room, /chess-bishop-tip/);
  assert.match(room, /chess-queen-crown/);
  assert.match(room, /chess-queen-crown-ring/);
  assert.match(room, /chess-queen-crown-spike/);
  assert.match(room, /chess-king-orb/);
  assert.match(room, /chess-king-cross/);
  assert.match(room, /chessSetHeight = 0\.62/);
  assert.match(room, /0\.84 \+ printProgress \* chessSetHeight/);
  assert.match(room, /printer-y-bed/);
  assert.match(room, /printer-z-gantry/);
  assert.match(room, /printer-z-lead-screw/);
  assert.match(room, /printer-bed-clip/);
  assert.match(room, /printer-gantry-wheel/);
  assert.match(room, /printer-bed-spring/);
  assert.match(room, /printer-extruder-fan-grille/);
  assert.match(room, /printer-hotend-assembly/);
  assert.match(room, /printer-hotend-heatsink-fin/);
  assert.match(room, /printer-hotend-heat-break/);
  assert.match(room, /printer-hotend-heater-block/);
  assert.match(room, /printer-hotend-silicone-sock/);
  assert.match(room, /printer-hotend-heating-cartridge/);
  assert.match(room, /printer-hotend-thermistor/);
  assert.match(room, /printer-brass-nozzle-cone/);
  assert.match(room, /printer-nozzle-fine-tip/);
  assert.match(room, /printer-active-filament-thread/);
  assert.match(room, /printer-filament-feed-tube/);
  assert.match(room, /printer-x-axis-belt/);
  assert.match(room, /printer-stepper-motor/);
  assert.match(room, /printer-spool-black/);
  assert.match(room, /printer-spool-orange/);
  assert.match(room, /printer-spool-purple/);
  assert.match(room, /printer-spool-white/);
  assert.match(room, /createPrinterSpool/);
  assert.match(room, /printableParts/);
  assert.doesNotMatch(room, /desk-cyan-edge/);
  assert.doesNotMatch(room, /desk-amber-edge/);
  assert.match(room, /desktop-mouse-pad-seated/);
  assert.match(room, /new THREE\.CircleGeometry\(1\.85, 56\)/);
  assert.match(room, /cameraGroup\.position\.set\(-5\.46, 2\.78, 0\.34\)/);
  assert.match(room, /racketMount/);
  assert.match(room, /racketMount\.position\.set\(-4\.5, 2\.42, -4\.16\)/);
  assert.match(room, /racket\.position\.set\(-4\.35, 3\.52, -4\.08\)/);
  assert.match(room, /camera-beveled-body/);
  assert.match(room, /camera-focus-ring/);
  assert.match(room, /camera-rear-lcd/);
  assert.match(room, /camera-viewfinder/);
  assert.match(room, /camera-lens-aperture/);
  assert.match(room, /camera-lens-glint/);
  assert.match(room, /camera-hot-shoe/);
  assert.match(room, /ceilingPanelColors/);
  assert.doesNotMatch(room, /let brace/);
  assert.match(room, /PRINT_DURATION_MS = 180_000/);
  assert.match(room, /drawPrinterDisplay/);
  assert.match(room, /THREE-MINUTE PRINT COMPLETE/);
  assert.match(room, /CHESS SET READY/);
  assert.doesNotMatch(room, /dagger/i);
  assert.match(room, /playSiteSfx\("complete"\)/);
  assert.match(room, /playSiteSfx\("open"\)/);
  assert.doesNotMatch(room, /cat\.jpg/i);
  assert.match(room, /bottom-shelf-printed-katana/);
  assert.match(room, /shelf-katana-unified-curved-blade/);
  assert.match(room, /shelf-katana-habaki/);
  assert.doesNotMatch(room, /shelf-katana-white-spine/);
  assert.match(room, /shelf-katana-tsuba/);
  assert.match(room, /shelf-katana-kashira/);
  assert.match(room, /shelf-katana-lacquered-scabbard/);
  assert.match(room, /shelf-katana-grip-diamond/);
  assert.match(room, /hidden-server-beacon/);
  assert.match(room, /PRINTED RELIC AWAKENED/);
  assert.match(room, /SERVER BEACON ONLINE/);
  assert.match(room, /PURR MODE UNLOCKED/);
  assert.match(room, /SUNROOM PALETTE UNLOCKED/);
  assert.match(room, /BADMINTON/);
  assert.match(room, /READING SHELF/);
  assert.match(room, /PHOTOGRAPHY/);
  assert.match(room, /shelf-fastener/);
  assert.match(room, /book-rounded-cover/);
  assert.match(room, /book-page-block/);
  assert.match(room, /book-spine-label-band/);
  assert.match(room, /racket-single-shaft/);
  assert.match(room, /physicalMaterial\("#25313a"/);
  assert.match(room, /material\("#21162f"/);
  assert.match(room, /"#46545b"/);
  assert.match(room, /racket-tapered-shaft-ferrule/);
  assert.match(room, /racket-shaft-collar/);
  assert.match(room, /racket-wall-mount-plate/);
  assert.match(room, /racket-wall-hook-arm/);
  assert.match(room, /racket-wall-hook-tip/);
  assert.match(room, /racket-string-grommet/);
  assert.doesNotMatch(room, /racket-throat/);
  assert.doesNotMatch(room, /racket-t-joint/);
  assert.match(room, /cat-tail-3d/);
  assert.match(room, /cat-patterned-bandana/);
  assert.match(room, /cat-name-tag/);
  assert.match(room, /cat-whisker/);
  assert.match(room, /cat-paw-toe/);
  assert.match(room, /cat-eye-glint/);
  assert.match(room, /cat-brow-fur/);
  assert.match(room, /cat-chest-fur-patch/);
  assert.match(room, /room-rear-baseboard/);
  assert.match(room, /desk-adjustable-foot/);
  assert.match(room, /cat-rug-yarn-ball/);
  assert.match(room, /cat-rug-loose-yarn/);
  assert.match(room, /cat-rug-toy-mouse/);
  assert.match(room, /cat-rug-water-bowl/);
  assert.match(room, /TubeGeometry/);
  assert.match(room, /raycaster\.intersectObjects/);
  assert.match(room, /touchOffsets/);
  assert.match(room, /phonePortrait/);
  assert.match(room, /phoneLandscape/);
  assert.match(room, /beginCameraMove/);
  assert.match(room, /RETURNING TO DEFAULT VIEW/);
  assert.match(room, /dismissObjectFile/);
  assert.match(room, /Close object file and keep the current camera view/);
  assert.match(room, /Close object file and return to the default room view/);
  assert.match(room, /OUTSIDE \/ FREE CAMERA/);
  assert.match(room, /focusObject/);
  assert.match(room, /room-popup/);
  assert.match(room, /setActiveKey/);
  assert.match(room, /controls\.enableZoom = true/);
  assert.match(room, /controls\.minDistance = 2\.1/);
  assert.match(room, /controls\.mouseButtons\.RIGHT = THREE\.MOUSE\.PAN/);
  assert.match(room, /controls\.touches\.ONE = THREE\.TOUCH\.PAN/);
  assert.match(room, /controls\.touches\.TWO = THREE\.TOUCH\.DOLLY_ROTATE/);
  assert.match(room, /coarsePointer/);
  assert.match(room, /Right drag \/ move camera/);
  assert.match(room, /contextmenu/);
  assert.match(room, /cameraOffset/);
  assert.match(room, /compositionShift/);
  assert.match(room, /room-focus-active/);
  assert.match(room, /room-default-view/);
  assert.match(room, /markCameraExploring/);
  assert.match(room, /targetOffset/);
  assert.match(room, /room-popup-sections/);
  assert.match(room, /pointerParallax/);
  assert.match(room, /pointerParallaxTarget/);
  assert.match(room, /arcHeight/);
  assert.doesNotMatch(room, /interactionMarkers/);
  assert.doesNotMatch(room, /addInteractionMarker/);
  assert.match(room, /MOVE \/ DRAG \/ SELECT/);
  assert.match(room, /SCENE RESPONSIVE/);
  assert.match(room, /affan-lab-discoveries/);
  assert.match(room, /viewed/);
  assert.doesNotMatch(room, /rack-fan-/);
  assert.doesNotMatch(room, /const rackFans/);
  assert.doesNotMatch(room, /CYBER ROVER/);
  assert.doesNotMatch(room, /driveState/);
  assert.doesNotMatch(room, /rover-pad/);
  assert.doesNotMatch(room, /from "next\/link"/);
  assert.doesNotMatch(room, /href: "\/work\//);
  assert.doesNotMatch(room, /href: "\/interests\//);

  assert.match(desktopOs, /AFFAN_OS portfolio desktop/);
  assert.match(desktopOs, /Search files and apps/);
  assert.match(desktopOs, /Projects/);
  assert.match(desktopOs, /Network Labs/);
  assert.match(desktopOs, /Education/);
  assert.match(desktopOs, /Experience/);
  assert.match(desktopOs, /Interests/);
  assert.match(desktopOs, /Contact/);
  assert.match(desktopOs, /Inspiration/);
  assert.match(desktopOs, /React Bits\.url/);
  assert.match(desktopOs, /Rachel Wei\.url/);
  assert.match(desktopOs, /Rachel Wei Source\.url/);
  assert.match(desktopOs, /Three\.js\.url/);
  assert.match(desktopOs, /Three\.js Resources\.url/);
  assert.match(desktopOs, /Poly Haven\.url/);
  assert.match(desktopOs, /Studio Reference\.url/);
  assert.match(desktopOs, /Perry Wang\.url/);
  assert.match(desktopOs, /3D Assets Directory\.url/);
  assert.match(desktopOs, /TurboSquid Review\.url/);
  assert.match(assetCredits, /Creative Commons CC0 1\.0 Universal/);
  assert.match(assetCredits, /Rajil Jose Macatangay/);
  assert.doesNotMatch(assetCredits, /retained but not loaded/);
  assert.match(assetCredits, /not downloadable/);
  assert.match(designReferences, /Rachel Wei source repository/);
  assert.match(designReferences, /Perry Wang portfolio/);
  assert.match(designReferences, /Three\.js Resources 3D-assets directory/);
  assert.match(designReferences, /No TurboSquid model is included/);
  assert.match(desktopOs, /Archtech Operations\.project/);
  assert.match(desktopOs, /SSIK Consulting\.project/);
  assert.match(desktopOs, /Ghayas Sher/);
  assert.match(desktopOs, /private, local-first SSIK Intelligence V1 platform/);
  assert.match(desktopOs, /79 automated tests/);
  assert.match(desktopOs, /sil6428\.github\.io\/SSIK-website/);
  assert.match(desktopOs, /File Integrity Monitor\.py/);
  assert.match(desktopOs, /github\.com\/sil6428\/file-integrity-monitor/);
  assert.match(desktopOs, /Secure File Transfer\.py/);
  assert.match(desktopOs, /13 automated tests/);
  assert.match(desktopOs, /Secure Messaging Platform\.wip/);
  assert.match(desktopOs, /Private · work in progress/);
  assert.match(desktopOs, /explicitly unfinished messaging platform/);
  assert.doesNotMatch(desktopOs, /CICIDS2017\.research/);
  assert.doesNotMatch(desktopOs, /github\.com\/sil6428\/secure-file-transfer/);
  assert.doesNotMatch(desktopOs, /github\.com\/sil6428\/secure-messaging-platform/);
  assert.match(desktopOs, /Event Planner\.js/);
  assert.match(desktopOs, /Resume\.pdf/);
  assert.match(desktopOs, /Affan_Shaikh_Resume\.pdf\?v=2026-09-01-secure-transfer#view=FitH/);
  assert.match(desktopOs, /Affan Shaikh resume PDF/);
  assert.match(desktopOs, /Ontario Tech\.txt/);
  assert.match(desktopOs, /Security\+\.plan/);
  assert.match(desktopOs, /Work Experience\.txt/);
  assert.match(desktopOs, /Volunteer Work\.txt/);
  assert.match(desktopOs, /Badminton\.txt/);
  assert.match(desktopOs, /3D Printing\.txt/);
  assert.match(desktopOs, /affan-os-terminal-input/);
  assert.match(desktopOs, /submitTerminal/);
  assert.match(desktopOs, /affan-os-terminal-toggle/);
  assert.match(desktopOs, /resolveShellFolder/);
  assert.match(desktopOs, /findShellItem/);
  assert.match(desktopOs, /Bash navigation/);
  assert.match(desktopOs, /handleTerminalInputKeyDown/);
  assert.match(desktopOs, /grep <term> <file>/);
  assert.match(desktopOs, /PORTFOLIO_MODE=interactive/);
  assert.match(desktopOs, /iconOrder/);
  assert.match(desktopOs, /Learning Log/);
  assert.match(desktopOs, /public entries/);
  assert.match(desktopOs, /github\.com\/sil6428\/learning-log/);
  assert.match(desktopOs, /LearningLogMarkdown/);
  assert.match(desktopOs, /learning-log-\$\{month\.year\}-\$\{month\.month\}/);
  assert.doesNotMatch(desktopOs, /Learning Log\.private/);
  assert.doesNotMatch(desktopOs, /Private project record/);
  assert.match(learningLog, /learning-log-entry-2026-08-16/);
  assert.match(learningLog, /Started a cybersecurity research reproduction project/);
  assert.match(learningLog, /learning-log-entry-2026-07-27/);
  assert.match(learningLog, /Set up a genuine learning log/);
  assert.match(desktopOs, /Networking · Configured IPv4 and IPv6/);
  assert.match(desktopOs, /Python · Built a SHA-256 file integrity monitor/);
  assert.match(desktopOs, /Three\.js · Built the interactive cyber lab/);
  assert.match(desktopOs, /Cloudflare Workers · Built and repeatedly deployed/);
  assert.match(desktopOs, /Google Workspace and web operations · Set up a nonprofit/);
  assert.match(desktopOs, /Minimize/);
  assert.match(desktopOs, /Maximize/);
  assert.match(desktopOs, /Return to 3D room/);
  assert.match(desktopOs, /aria-live="polite"/);

  assert.match(styles, /room-fluid-hint/);
  assert.match(styles, /affan-os-file-grid/);
  assert.match(styles, /affan-os-launcher/);
  assert.match(styles, /affan-os-taskbar/);
  assert.match(styles, /affan-os-desktop-groups/);
  assert.match(styles, /affan-os-resume-viewer/);
  assert.match(styles, /affan-os-terminal-history/);
  assert.match(styles, /@media \(pointer: coarse\)/);
  assert.match(styles, /\.room-canvas canvas \{ touch-action: none; \}/);
  assert.match(styles, /room-index-panel/);
  assert.match(styles, /room-side-index/);
  assert.match(styles, /room-target-cursor/);
  assert.match(styles, /room-click-spark/);
  assert.match(styles, /room-secret-toast/);
  assert.match(styles, /body\.room-default-view \.immersive-intro/);
  assert.match(styles, /body\.room-default-view \.room-fluid-hint/);
  assert.doesNotMatch(styles, /room-drive-hud/);
  assert.doesNotMatch(styles, /rover-pad/);
});
